In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2
import numpy as np

In [3]:
!pip3 install opencv-python

In [4]:
import cv2
import numpy as np

In [5]:
#load/read image
img = cv2.imread("E:\\New folder\\DataSets\\Modi.jpg",1)

In [6]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [7]:
#shape gives the dimensions of the image array
img.shape    #3 means there are 3components(RGB)

(1358, 1500, 3)

In [8]:
#display the image
cv2.imshow('PM',img)   #title (PM)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [9]:
#save image
cv2.imwrite("pm_b_w.jpg",img)

True

In [10]:
#Resize image
img = cv2.imread("E:\\New folder\\DataSets\\Modi.jpg")
resized_image = cv2.resize(img,(500,500))

gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

cv2.imshow('Modi Image', gray)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [11]:
img.shape[1]*0.5

750.0

In [12]:
img.shape[0]*0.5

679.0

In [13]:
#Face detection using HAAR Cascade Classifier

In [14]:
face_classifier = cv2.CascadeClassifier("E:\\New folder\\DataSets\\haarcascade_frontalface_default.xml")
#load image then convert it to grayscale
image = cv2.imread("E:\\New folder\\DataSets\\Modi.jpg")
image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

#tuning cascade Classifiers - detectMultiScale(input image,scale factor,min neighbors)
faces = face_classifier.detectMultiScale(gray,1.05,5)

In [15]:
print(faces)

[[205  79 217 217]]


In [16]:
if faces is ():
    print("No faces found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,100),1)
    
cv2.imshow('Face Detection',image)    

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Aspire 5\AppData\Local\Temp\ipykernel_12540\4217599461.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [17]:
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [18]:
#Face & eye detection using HAAR Cascade Classifiers in image 

In [19]:
face_classifier = cv2.CascadeClassifier("E:\\New folder\\DataSets\\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier("E:\\New folder\\DataSets\\haarcascade_eye.xml")

img = cv2.imread("E:\\New folder\\DataSets\\Modi.jpg")
resized_image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray,1.3,5)
if faces is ():
    print("No Face Found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h,x:x+w]
    roi_color = resized_image[y:y+h,x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        
cv2.imshow('img',resized_image)
cv2.waitKey(2000)

cv2.destroyAllWindows()

<>:9: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:9: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Aspire 5\AppData\Local\Temp\ipykernel_12540\3260775038.py:9: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [20]:
#capture a video

In [21]:
#Doing some face recognition with the webcam

In [22]:
import cv2
video = cv2.VideoCapture(0)  #0--webcam

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video',gray)
    if cv2.waitKey(1)==ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()    
    

In [23]:
#defining a function that will do the detection
face_cascade = cv2.CascadeClassifier("E:\\New folder\\DataSets\\haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("E:\\New folder\\DataSets\\haarcascade_eye.xml")

def detect(gray,frame):
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h,x:x+w]
        roi_color = frame[y:y+h,x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray,1.1,3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame

#doing some face recognition with the webcam
video = cv2.VideoCapture(0)

while True:
    check, frame=video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,frame)
    cv2.imshow('Video',canvas)
    if cv2.waitKey(1)==ord('q'):
        break
        
video.release() 
cv2.destroyAllWindows()
    

In [24]:
#Pedistrian detection

In [25]:
import cv2
#create our body classifier
body_classifier = cv2.CascadeClassifier("E:\\New folder\\DataSets\\haarcascade_fullbody.xml")
 
cap = cv2.VideoCapture("E:\\New folder\\DataSets\\walking.avi")  

while cap.isOpened():
    check, frame=cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    bodies = body_classifier.detectMultiScale(gray,1.2,3)
    
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('Pedestrians',frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()
       
        
    

In [26]:
import time
car_classifier = cv2.CascadeClassifier("E:\\New folder\\DataSets\\haarcascade_car.xml")
cap = cv2.VideoCapture("E:\\New folder\\DataSets\\cars.avi")
while cap.isOpened():
    
    time.sleep(.05)
    
    check, frame= cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    cars =car_classifier.detectMultiScale(gray,1.4,2)
    
    for (x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('Cars',frame)
        
    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()